//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YSUIB.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ambion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ambion()
        {
            this.Professors = new HashSet<Professor>();
        }
    
        public long Id { get; set; }
        public Nullable<long> FacultyId { get; set; }
        public Nullable<long> NameT { get; set; }
        public Nullable<long> ManagerWorkerId { get; set; }
    
        public virtual Faculty Faculty { get; set; }
        public virtual Translation NameTranslation { get; set; }
        public virtual Worker Worker { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Professor> Professors { get; set; }
    }
}
