//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YSUIB.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public long Id { get; set; }
        public long CategoryId { get; set; }
        public long UserId { get; set; }
        public Nullable<long> PictureId { get; set; }
        public System.DateTime StoredDateTime { get; set; }
        public System.DateTime PublishDateTime { get; set; }
        public Nullable<System.DateTime> LastEditDateTime { get; set; }
        public long Views { get; set; }
        public long TitleT { get; set; }
        public Nullable<long> DescribtionTT { get; set; }
        public long TextTT { get; set; }
    
        public virtual ArticleCategory ArticleCategory { get; set; }
        public virtual Picture Picture { get; set; }
        public virtual Translation TitleTranslation { get; set; }
        public virtual TranslationText DescribtionTranslation { get; set; }
        public virtual TranslationText TextTranslation { get; set; }
        public virtual User User { get; set; }
    }
}
