//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YSUIB.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public long Id { get; set; }
        public string FilePath { get; set; }
        public Nullable<System.DateTime> StoredDateTime { get; set; }
        public long CategoryId { get; set; }
        public long NameT { get; set; }
        public Nullable<long> DescribtionTT { get; set; }
    }
}
