//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YSUIB.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lessons
    {
        public long Id { get; set; }
        public long CourseId { get; set; }
        public long ProfessorId { get; set; }
        public int Year { get; set; }
        public int Semester { get; set; }
        public int Week { get; set; }
        public int WeekDay { get; set; }
        public int Hour { get; set; }
        public long ClassroomId { get; set; }
    }
}
