//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YSUIB.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesson
    {
        public long Id { get; set; }
        public long CourseId { get; set; }
        public long ProfessorId { get; set; }
        public int Year { get; set; }
        public int Semester { get; set; }
        public long WeekId { get; set; }
        public long WeekDayId { get; set; }
        public int Hour { get; set; }
        public long ClassroomId { get; set; }
        public long SubjectId { get; set; }
    
        public virtual Classroom Classroom { get; set; }
        public virtual Course Course { get; set; }
        public virtual Professor Professor { get; set; }
        public virtual Subject Subject { get; set; }
        public virtual Week Week { get; set; }
        public virtual WeekDay WeekDay { get; set; }
    }
}
