//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YSUIB.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Link
    {
        public long Id { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public string OptionsJSON { get; set; }
        public string ExternalUrl { get; set; }
    }
}
