//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YSUIB.Models.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UniversityEntities : DbContext
    {
        public UniversityEntities()
            : base("name=UniversityEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ambions> Ambions { get; set; }
        public virtual DbSet<ArticleCategories> ArticleCategories { get; set; }
        public virtual DbSet<Articles> Articles { get; set; }
        public virtual DbSet<BookCategories> BookCategories { get; set; }
        public virtual DbSet<Books> Books { get; set; }
        public virtual DbSet<Classrooms> Classrooms { get; set; }
        public virtual DbSet<Courses> Courses { get; set; }
        public virtual DbSet<Facultyes> Facultyes { get; set; }
        public virtual DbSet<Files> Files { get; set; }
        public virtual DbSet<IcoFiles> IcoFiles { get; set; }
        public virtual DbSet<Languages> Languages { get; set; }
        public virtual DbSet<Lessons> Lessons { get; set; }
        public virtual DbSet<Pictures> Pictures { get; set; }
        public virtual DbSet<Professors> Professors { get; set; }
        public virtual DbSet<RatingCriteria> RatingCriteria { get; set; }
        public virtual DbSet<Specializations> Specializations { get; set; }
        public virtual DbSet<Staff> Staff { get; set; }
        public virtual DbSet<Students> Students { get; set; }
        public virtual DbSet<Subjects> Subjects { get; set; }
        public virtual DbSet<Translations> Translations { get; set; }
        public virtual DbSet<TranslationsText> TranslationsText { get; set; }
        public virtual DbSet<Tree> Tree { get; set; }
        public virtual DbSet<UserRating> UserRating { get; set; }
        public virtual DbSet<UserRequests> UserRequests { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<WeekDays> WeekDays { get; set; }
        public virtual DbSet<Weeks> Weeks { get; set; }
    }
}
