//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YSUIB.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRequest
    {
        public long Id { get; set; }
        public long UserId { get; set; }
        public System.DateTime RequestDateTime { get; set; }
        public string RequestUrl { get; set; }
        public string Ip { get; set; }
        public string Browser { get; set; }
    
        public virtual User User { get; set; }
    }
}
