//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YSUIB.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public long Id { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public long FirstNameT { get; set; }
        public long MiddleNameT { get; set; }
        public long LastNameT { get; set; }
        public System.DateTime BirthDate { get; set; }
        public System.DateTime RegisterDateTime { get; set; }
        public System.DateTime LastLoginDateTime { get; set; }
    }
}
